### ISSUE TITLE
Still working on this

### ISSUE THREAD

**Issue by kennetpostigo** [fxfactorial/ocaml-express#2]
This would be kickass and I would use this all the time. Are you still working on this?

**Comment by fxfactorial** [comment]
The plan is the rewrite it in bucklescript

**Comment by fxfactorial** [comment]
I will be starting on it soon and all npm packages I did bindings for.

**Comment by kennetpostigo** [comment]
Sweet @fxfactorial ! Big fan of your work and your blog! Very informative and useful. I saw someone complain about web api's and reason not being cross platform, and I think it's a valid point. So when I see something like express being remade in reason/ocaml it was exciting. Although express may be overkill to remake. I think a better simpler approach would be to remake [`micro`](https://github.com/zeit/micro) which is blowing up in JS community for its simplicity

**Comment by fxfactorial** [comment]
That's very kind of you to say and gives me more motivation to do the bindings 😃
